# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 01:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('nombre_convenio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='datosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=150)),
                ('comuna', models.CharField(max_length=150)),
                ('fono_celular', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe ser ingresado en formato: '+56999999999'. hasta 11 digitos.", regex='^\\+?1?\\d{11}$')])),
                ('fono_fijo', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe ser ingresado en formato: '+56999999999'. hasta 11 digitos.", regex='^\\+?1?\\d{11}$')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('rut', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Ingresar el rut con formato '11111111-k'.", regex='^\\d{1,2}\\d{6}[\\-][0-9kK]{1}')])),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('rut', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Ingresar el rut con formato '11.111.111-k'.", regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[\\-][0-9kK]{1}')])),
                ('razon_social', models.CharField(max_length=80)),
                ('rut_representante', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Ingresar el rut con formato '11.111.111-k'.", regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[\\-][0-9kK]{1}')])),
                ('nombre_representante', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=150)),
                ('comuna', models.CharField(max_length=150)),
                ('fono_celular', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe ser ingresado en formato: '+56999999999'. hasta 11 digitos.", regex='^\\+?1?\\d{11}$')])),
                ('fono_fijo', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe ser ingresado en formato: '+56999999999'. hasta 11 digitos.", regex='^\\+?1?\\d{11}$')])),
                ('fono_fax', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El telefono debe ser ingresado en formato: '+56999999999'. hasta 11 digitos.", regex='^\\+?1?\\d{11}$')])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_movil', models.CharField(default='00', max_length=4)),
                ('agno', models.IntegerField(default=2000)),
                ('valor_mes', models.IntegerField(default=1)),
                ('datos_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.datosPersonales')),
            ],
        ),
        migrations.CreateModel(
            name='periodoFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_Inicio', models.DateField(default=datetime.datetime(2018, 1, 14, 1, 50, 13, 111209, tzinfo=utc))),
                ('fecha_Fin', models.DateField(default=datetime.datetime(2018, 1, 14, 1, 50, 13, 111252, tzinfo=utc))),
                ('detalle', models.TextField(validators=[django.core.validators.MaxLengthValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='talonario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('numero_convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.convenio')),
                ('numero_movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.movil')),
            ],
        ),
        migrations.CreateModel(
            name='talonarioVale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_talonario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.talonario')),
            ],
        ),
        migrations.CreateModel(
            name='tipoMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('tipo_movil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('tipo_persona', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipoVale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('tipo_vale', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('correlativo', models.FloatField(default=None)),
                ('direccion_origen', models.CharField(max_length=150)),
                ('direccion_destino', models.CharField(max_length=150)),
                ('observacion', models.TextField(validators=[django.core.validators.MaxLengthValidator(300)])),
                ('responsable_ingreso', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.convenio')),
                ('datoPeriodoFacturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.periodoFacturacion')),
                ('datos_movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.movil')),
                ('tipo_Vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.tipoVale')),
            ],
        ),
        migrations.AddField(
            model_name='talonariovale',
            name='datos_vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.vale'),
        ),
        migrations.AddField(
            model_name='movil',
            name='tipo_movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.tipoMovil'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.tipoPersona'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='datos_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.datosPersonales'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='datos_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.empresa'),
        ),
    ]
