# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appIntranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talonariovale',
            name='numero_vale',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='datos_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.DatosPersonales'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='datos_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Empresa'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.TipoPersona'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='datos_chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.DatosPersonales'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='tipo_movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.TipoMovil'),
        ),
        migrations.AlterField(
            model_name='periodofacturacion',
            name='fecha_Fin',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 16, 32, 3, 70660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='periodofacturacion',
            name='fecha_Inicio',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 16, 32, 3, 70618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talonario',
            name='numero_convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Convenio'),
        ),
        migrations.AlterField(
            model_name='talonario',
            name='numero_movil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Movil'),
        ),
        migrations.AlterField(
            model_name='talonariovale',
            name='datos_talonario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Talonario'),
        ),
        migrations.AlterField(
            model_name='talonariovale',
            name='datos_vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Vale'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Convenio'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='datoPeriodoFacturacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.PeriodoFacturacion'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='datos_movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.Movil'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='tipo_Vale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIntranet.TipoVale'),
        ),
    ]
